Mapnik Python bindings expect 8-bit strings, not unicode
This fixes following error:
Traceback (most recent call last):
  File "./nik4.py", line 602, in <module>
    run(options)
  File "./nik4.py", line 369, in run
    mapnik.load_map_from_string(m, style_xml, False, style_path)
        Boost.Python.ArgumentError: Python argument types in
    mapnik._mapnik.load_map_from_string(Map, unicode, bool, str)
      did not match C++ signature:
    load_map_from_string(mapnik::Map {lvalue},
      std::__cxx11::basic_string<char, std::char_traits<char>,
      std::allocator<char> >)
    load_map_from_string(mapnik::Map {lvalue},
      std::__cxx11::basic_string<char, std::char_traits<char>,
      std::allocator<char> >, bool)
    load_map_from_string(mapnik::Map {lvalue},
      std::__cxx11::basic_string<char, std::char_traits<char>,
      std::allocator<char> >, bool, std::__cxx11::basic_string<char,
      std::char_traits<char>, std::allocator<char> >)